Guided Sail
community-boating/cbidb-api pull request #9
Opened 2024-05-24 00:03 UTC by alexjpbanks14

Guided sail back end functionality. In order for the create class to function properly the PLSQL package must be updated to have the create_class_instance_vc procedure in the ap_class_pkg.

2024-05-29 18:12 UTC, coleji requested changes

2024-05-29 18:12 UTC, coleji commented on app/com/coleji/neptune/Core/RelationalBroker.scala
> +			println("CALLABLE", callable)
remove debug

2024-05-29 18:12 UTC, coleji commented on app/org/sailcbi/APIServer/Api/Endpoints/Member/GetApClassesForCalendar.scala
> +			Future(Ok(Json.toJson(response)))
Not sure I understand the purpose for this api change.  The frontend will always have the personId of the session globally already, for AP there is only ever one

2024-05-29 18:12 UTC, coleji commented on app/org/sailcbi/APIServer/Entities/cacheable/yearlydate/YearlyDateCache.scala
> +    val qb = QueryBuilder.from(YearlyDate)
Always specify fields with .select(), although this cache doesnt seem to be referenced

2024-05-29 18:12 UTC, coleji commented on app/org/sailcbi/APIServer/IO/Portal/PortalLogic.scala
> +					|i.cancelled_datetime
not referenced

2024-05-29 18:12 UTC, coleji commented on app/org/sailcbi/APIServer/Api/Endpoints/Member/ApGuidedSailController.scala
> +      val currentMonthDatetime = LocalDate.now().withYear(forYear).withMonth(forMonth)
Always use PA.now() so the server can be time traveled

2024-05-29 18:12 UTC, coleji commented on app/org/sailcbi/APIServer/Logic/ApClassLogic.scala
> +	private val GUIDED_SAIL_CLASS_FORMAT = 1101
Move this to org.sailcbi.APIServer.Entities.MagicIds

2024-05-29 18:12 UTC, coleji commented on app/org/sailcbi/APIServer/Logic/ApClassLogic.scala
> +			updateApClassCancelled(rc, "ap_class_instances", "sysdate", currentInstanceId)
use util_pkg.get_sysdate rather than raw sysdate so the server can be time traveled

2024-05-29 18:12 UTC, coleji commented on app/org/sailcbi/APIServer/Logic/ApClassLogic.scala
> +			updateApClassCancelled(rc, "ap_class_instances", "sysdate", currentInstanceId)
use eg ApClassInstance.entityName rather than hardcode table names

2024-05-29 18:12 UTC, coleji commented on app/org/sailcbi/APIServer/Logic/ApClassLogic.scala
> +		val forMonthEnd = forMonth.plusMonths(1).minusDays(1)
does this also need withDayOfMonth() ?

2024-05-29 18:12 UTC, coleji commented on app/org/sailcbi/APIServer/Logic/ApClassLogic.scala
> +		val startAndSunsetTimes = sunsetTimes.map(a => (a, getStartTime(a.toLocalDate, jpClassSchedule))).filter(a => a._1.isAfter(LocalDateTime.now()))
replace LocalDateTime.now() with rc.PA.now()

2024-06-08 16:20 UTC, coleji commented on app/org/sailcbi/APIServer/Api/Endpoints/Member/ApGuidedSailController.scala
> +      val currentMonthDatetime = LocalDate.now().withYear(forYear).withMonth(forMonth)
`val currentMonthDatetime = LocalDate.now()` replace with `val currentMonthDatetime = PA.now().toLocalDate()`

2024-06-08 16:28 UTC, coleji commented
ap_class_pkg.create_class_instance_vc added to prod

2024-06-08 21:59 UTC, alexjpbanks14 commented on app/com/coleji/neptune/Core/RelationalBroker.scala
> +			println("CALLABLE", callable)
Gone

2024-06-08 22:07 UTC, alexjpbanks14 commented on app/org/sailcbi/APIServer/Api/Endpoints/Member/GetApClassesForCalendar.scala
> +			Future(Ok(Json.toJson(response)))
Yeah I realized that was a bad idea to change the API shape, so its back how it was before and I just pulled the personId from the welcomeAP endpoint, let me know if I'm missing something obvious but I didn't see a better way to get it other than maybe creating get person id endpoint or something.

2024-06-09 18:12 UTC, merged